name: veu

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: veu/yarn.lock
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test
